import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

// Define an interface for your newsletter subscription DTO
export interface NewsletterSubscription {
  id?: number; // Optional as it's generated by backend
  email: string;
  subscriptionDate?: string; // Optional, backend sets this
  active?: boolean; // Optional, backend sets this
}

@Injectable({
  providedIn: 'root'
})
export class NewsletterService {
  private apiUrl = 'http://localhost:8081/api/newsletter'; // Your backend URL for newsletter

  constructor(private http: HttpClient) { }

  /**
   * Subscribes an email to the newsletter.
   * @param email The email to subscribe.
   * @returns An Observable of the NewsletterSubscription.
   */
  subscribe(email: string): Observable<NewsletterSubscription> {
    // Backend expects a DTO with an email field in the request body
    return this.http.post<NewsletterSubscription>(`${this.apiUrl}/subscribe`, { email });
  }

  /**
   * Unsubscribes an email from the newsletter.
   * @param email The email to unsubscribe.
   * @returns An Observable indicating completion.
   */
  unsubscribe(email: string): Observable<void> {
    // Backend expects a DTO with an email field in the request body
    return this.http.post<void>(`${this.apiUrl}/unsubscribe`, { email });
  }
}